version: '2.1'

networks:
  monitor-net:
    driver: bridge

volumes:
    prometheus_data: {}
    grafana_data: {}

services:

  metric-service:
    container_name: metric-service
    image: monar2/metric-service
    networks:
      - monitor-net
    build: ../
    ports:
      - "8080:8080"

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus
    networks:
      - monitor-net
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    links:
      -  metric-service

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana
    networks:
      - monitor-net
    ports:
      - "3000:3000"